### ISSUE TITLE
Notes from Radek

### ISSUE THREAD

**Issue by mukrop** [teaching-lab/reflective-diary#11]
From Radek: Is it not a seminar tutor's reflective diary? Or a Teaching assistant's reflective diary?

You're using the revised Bloom taxonomy (update name, year), maybe mention the existence of the second dimension.

CZ: designovat → navrhovat (?)

**Comment by svabensky** [comment]
Name change: no, leave as is.
Bloom's taxonomy: updated.
CZ wording: updated.
